const Licensesobj = require('./Licenseobj');

// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  if (license === "none") {
    return ``;
  }
  else {
    return `![badge](https://img.shields.io/badge/license-${license}-brightgreen)
    `
  }
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  if (license === "none") {
    return ``;
  }
  else {
    return `(${license})`
  }
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  if (license === "none") {
    return `No License was used`;
  }
  else {
    return `This application is covered by the [${license}]`
  }
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  const licenseLink = Licensesobj.getLicenseLink(data.license);
  const licenseAbrv = Licensesobj.getLicenseAbrv(data.license);
  const renderedbadge = renderLicenseBadge(licenseAbrv);
  const renderedlink = renderLicenseLink(licenseLink);
  const renderedText = renderLicenseSection(data.license);
  return `# ${data.title}
  ${renderedbadge}
  ## Description

  ${data.description}

  ## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Questions](#questions)

  ## Installation
  ${data.installation}

  ## Usage
  ${data.usage}

  ## License
  ${renderedbadge}
  ${renderedText}${renderedlink}. 

  ## Contributing
  ${data.contributing}

  ## Tests
  ${data.tests}

  ## Questions


  Find more info on GitHub: [${data.githubUser}](https://github.com/${data.githubUser})
  
  Email with any questions: [${data.email}](mailto:${data.email})




  This README was generated by [README-gen8r](https://github.com/Nathanpatnaude/readme_gen8r)
`;
}

module.exports = generateMarkdown;
